
GET http://localhost:4358/api/todos
Content-Type: application/json


###
GET http://localhost:4358/api/v1/todos/10

###
POST http://localhost:4358/api/v1/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJuYW1lIjoiZWdhIiwiZW1haWwiOiJlZ2FAZ21haWwuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDEtMjlUMDg6NDU6MzIuMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI2LTAxLTI5VDA4OjQ1OjMyLjAwMFoifSwiaWF0IjoxNzY5Njc2Mzg5LCJleHAiOjE3Njk2Nzk5ODl9.-WUNrOyeYRNwTNkAbXus-JgyT90aniyBqYHJytnq6KM

{
    "title": "New anjay",
    "status": "pending",
    "priority": "medium",
    "due_date": "2026-12-31"
}

###
PUT http://localhost:4358/api/v1/todos/2
Content-Type: application/json

{
    "title": "Updated Title",
    "status": "pending",
    "priority": "high",
    "due_date": "2026-11-30",
    "description": "ini di update dei"
}

###
DELETE http://localhost:4358/api/v1/todos/10

###
GET http://localhost:4358/api/v1/categories

###
GET http://localhost:4358/api/v1/categories/3


###
POST http://localhost:4358/api/v1/categories
Content-Type: application/json

{
    "name": "New Category"
}

### 
PUT http://localhost:4358/api/v1/categories/3
Content-Type: application/json

{
    "name": "Updated Category Name"
}

###
DELETE http://localhost:4358/api/v1/categories/5

###
GET http://localhost:4358/api/v1/todosPriority

###
GET http://localhost:4358/api/v1/todosStatus

###
GET http://localhost:4358/api/v1/enum

###
GET http://localhost:4358/api/v1/query/testing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJuYW1lIjoiZWdhIiwiZW1haWwiOiJlZ2FAZ21haWwuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDEtMjlUMDg6NDU6MzIuMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI2LTAxLTI5VDA4OjQ1OjMyLjAwMFoifSwiaWF0IjoxNzY5NjgwMzc4LCJleHAiOjE3Njk2ODM5Nzh9.I33nAUU6mSRyRFlCku1uFDACFd_asIASndb0LI8GzOk

###
POST http://localhost:4358/api/v1/tes